### ISSUE TITLE
Error building index.js

### ISSUE THREAD

**Issue by genaro-picazo** [adjeteyadjei/angular-typescript-starter#1]
Getting the following error when running the `npm start` command:

```
ERROR in ./app/app.ts
Module build failed: [object Object]
 @ ./index.js 18:11-31
```

**Comment by adjeteyadjei** [comment]
Sorry for the late response. The issue is coming from a change in version of typescript loader.
I have updated the package.json file.
Please delete the node_modules folder and run `npm install` again.
